### ISSUE TITLE
Conflict with Avada sticky header

### ISSUE THREAD

**Issue by bboerendans** [ahmedkaludi/Easy-Table-of-Contents#120]
On pages where the ToC is displayed, the header of the Avada theme is not working as exepected anymore.

Normal behaviour:
When a visitor scrolls down, the header becomes hidden. When a user scrolls back up, the header becomes visible.

When this ToC plugin is displayed on the page behaviour:
When a visitor scrolls down, the header sticks on top of the screen with a transparent background. 

Any ideas how to fix this? 

Wordpress 5.5.x
Avada 7.1.1 

No errors in console.

**Comment by akshaywali** [comment]
Hello [bboerendans](https://github.com/bboerendans) ,
We  were unable to recreate the sticky header error using Wordpress 5.5.3 and Avada 7.1.1. The Avada header was working fine in our testing .
If you are still facing the issue then please contact our support team so that they can help to resolve the issue.
