### ISSUE TITLE
Alternate Heading problem with Umlauts [Need Testing]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Easy-Table-of-Contents#148]
https://wordpress.org/support/topic/alternate-heading-problem-with-umlauts/#post-15501099

**Comment by iamwebrocker** [comment]
Hi, maybe related, I stumbled across a/the problem with Umlauts in headings, too.

In my case, the TOC wouldn't be inserted, turned out that the first heading in the post content had umlauts.
I debugged a bit futher, and found that headings with umlauts wouldn't get the replacement with the span and the id needed for the TOC anchors.

I found a fix for bith problems, but this maybe just for my use case and needs further investigation for unwanted side-effects.

in `includes/inc.string-functions.php`, line 300ff:

```
// If heading can not be found, let try decoding entities to see if it can be found.
				if ( false === $start ) {
					$needle = html_entity_decode(
						$needle,
						ENT_QUOTES,
						get_option( 'blog_charset' )
					);
					$start = mb_strpos( $string, $needle);
				}
```

change to

```
// If heading can not be found, let try decoding entities to see if it can be found.
				if ( false === $start ) {
					$needle = html_entity_decode(
						$needle,
						ENT_QUOTES,
						get_option( 'blog_charset' )
					);
                                       $string = html_entity_decode(
						$string,
						ENT_QUOTES,
						get_option( 'blog_charset' )
					);
					$start = mb_strpos( $string, $needle);
				}

```

and it worked for me.

I think this is because  `$string` had already been processed by WordPress "the_content" filter - so in there, Umlauts are already "html entities". Now the original code takes "my" normal Umlauts, tries to decode html entities (which changes nothing) and then compares this to the $string - and thus $start is still false.

If $string itself  html entities decoded, match is found and it works.

I don't think this is the optimal way, this is/was just a quick fix/proof of concept and, as said, maybe this only fixes my usecase with (german) Umlauts.

But maybe this helps to fix the bug in a better way. :)

Thanks for the cool plugin!

**Comment by iamwebrocker** [comment]
fyi, the problem with the umlauts still exists in the new version (2.0.24.1);
I had to re-apply my fix above to again get it to work:

```
if ( false === $start ) {
					$needle = html_entity_decode(
						$needle,
						ENT_QUOTES,
						get_option( 'blog_charset' )
					);
					$needle = str_replace(array('’','“','”'), array('\'','"','"'), $needle);
                    $string = html_entity_decode(
						$string,
						ENT_QUOTES,
						get_option( 'blog_charset' )
					);
					$start = mb_strpos( $string, $needle);
				}
```

**Comment by Zabi09** [comment]
Pushed in 2.0.28
