### ISSUE TITLE
Feature request for HTML5 <details> tag to expand / collapse feature of the plugin.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#153]
Reference ticket: https://wordpress.org/support/topic/feature-request-html5-expand-and-collapse/

**Comment by Lozula** [comment]
I just tested this on one my of my sites and it doesn't work - it adds a checkbox at the top of the TOC but it doesn't do anything.

If it helps, I edited the source of the plugin for another site for a css/html5 only collapsible TOC, and you can see how it works here:
https://www.findingtheuniverse.com/top-things-to-do-in-san-diego-california/

Rather than a checkbox, it uses the html5 <details> and <summary> tags. I edited the code in class.post.php as follows:

`$html .= '<div id="ez-toc-container" class="' . implode( ' ', $class ) . '"><details><summary>Table of Contents</summary>' . PHP_EOL;` (added the <details>and <summary> </summary>

Then just before the script is enqueued I closed the <details>

`$html .= '</details></div>' . PHP_EOL;
		
			// Enqueue the script.
			wp_enqueue_script( 'ez-toc-js' );`


I hope this helps :)

**Comment by Zabi09** [comment]
initially, we have created it with details and a summary tag but it was not working as expected so we have discussed it with our lead developers and created it with pure CSS only we have implemented it on a few websites and it is working fine please check this screenshot - https://prnt.sc/usiha_Jx9iv9

Please use our latest version 2.0.22 and check the functionality if you face any issues then please create a new ticket on GitHub and our team will look into it and fix it

**Comment by Lozula** [comment]
As an update, it wasn't working because I had checked the box "Prevent the loading the core CSS styles. When selected, the appearance options from above will be ignored."

However, now the initial toggle state is not working, I raised a new issue on WP: https://wordpress.org/support/topic/initial-toc-shown-even-when-initially-hide-is-chosen/
