### ISSUE TITLE
Gutenberg shortcode not working with for my site.

### ISSUE THREAD

**Issue by techtic30naitik** [ahmedkaludi/Easy-Table-of-Contents#653]
![sc1](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/33321681/2f05f696-2a5a-444d-951c-df2c3781419f)
![sc2](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/33321681/98ad9eb7-74fb-40d7-bcdc-536afe6ad082)

**Comment by Sanjeevsetu** [comment]
Hi @techtic30naitik 

Please cross check whether plugin 'Easy Table of Contents' is active.??

**Comment by Sanjeevsetu** [comment]
Strange. There might be some conflict with other plugins/theme or We have to make compatibility with them. Can you please share more information. Like how your website has been made, plugins used, theme so on.

Or better contact us via https://tocwp.com/contact

**Comment by Sanjeevsetu** [comment]
Hi @techtic30naitik 

Yes, we are on it. Allow us some time.

**Comment by Rkroy** [comment]
HI @techtic30naitik We've looked into this issue and noticed in your theme that you've been using get_the_content('','',$post->ID) to show content, is there any reason why you are using get_the_content instead of the_content() ?

If you use the below code, content is loading properly and we've tested it.
$postContent = apply_filters( 'the_content', get_the_content(), $post->ID );

**Comment by techtic30naitik** [comment]
@Sanjeevsetu @Rkroy Yup it's works for me. thank you for resolve this issue.

**Comment by Sanjeevsetu** [comment]
@techtic30naitik Nice to hear that issue has been solved. I am closing the ticket
