### ISSUE TITLE
Conflict issue with WPbakery plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#657]
Reference ticket:- https://magazine3.in/conversation/216066?folder_id=21

Description:-
User added the row below the title in WPbakery Builder in the post section, but when we click heading while on login, it goes to the top of the website.

Here is the issue video
https://monosnap.com/direct/hSv6c0BTq1eQlRUEWvbNGNB9CUq2jG

**Comment by Sanjeevsetu** [comment]
This issue is due to theme who is passing empty content to wordpress 'the_content' filter which is completely wrong. If any theme/plugin use apply_filters for the_content they must pass default content or modified content.

You can see issue in theme path : wp-content\themes\uncode\single.php. Line no. 369.

Wrong implementation == $get_content_appended = apply_filters('the_content', ''); 
Right implementation == $get_content_appended = apply_filters('the_content', $the_content);
