### ISSUE TITLE
Conflict issue with DIVI theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#749]
Ref ticket: https://magazine3.in/conversation/261031?folder_id=21

Description:-
When we activate our plugin, the below error shows in the front-end post section.

Error:-
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) in /home/jopadmin/public_html/1712237741154/wp-content/themes/Divi/includes/builder/class-et-builder-element.phpon line 20429

**Comment by akshaywali** [comment]
`$this->post->post_content = apply_filters( 'the_content', strip_shortcodes( $this->post->post_content ) );`

We were  basically stripping **shortcode** before running **the_content** filter

But issue was the builder themes like Divi uses   shortcodes for sections , rows and columns etc , which were not getting stripped using strip_shortcodes.[Reason might be that  this function removes only those shortcodes which are registered at the moment of the processing of this function]

So added a function **stripShortcodesButKeepContent** that  will strips all shortcodes  but retains their inner content. Retaining inner content is important since all heading , textarea are inside the sections /rows or column

**Comment by akshaywali** [comment]
pushed in version 2.0.67
